export * from "./authSlice";
export * from "./classroomSlice";
export * from "./majorSlice";
export * from "./planSlice";
export * from "./scheduleSlice";
export * from "./subjectSlice";
export * from "./teacherSlice";
export * from "./termSlice";
export * from "./uiSlice";
