export enum PublicRoutes {
  START = "/",
  LOGIN = "/login",
}

export enum PrivateRoutes {
  DASHBOARD = "/dashboard",
  MAJOR = "/major",
  MAJOR_DETAIL = "/major/detail",
  MAJOR_CREATE = "/major/create",
  SUBJECT = "/subject",
  SUBJECT_DETAIL = "/subject/detail",
  SUBJECT_CREATE = "/subject/create",
  STUDENT = "/student",
  STUDENT_DETAIL = "/student/detail",
  STUDENT_CREATE = "/student/create",
  TEACHER = "/teacher",
  TEACHER_DETAIL = "/teacher/detail",
  TEACHER_CREATE = "/teacher/create",
  REQUEST = "/request",
  REQUEST_DETAIL = "/request/detail",
  REQUEST_CREATE = "/request/create",
  BUILDING = "/building",
  BUILDING_DETAIL = "/building/detail",
  BUILDING_CREATE = "/building/create",
  CLASSROOM = "/classroom",
  CLASSROOM_DETAIL = "/classroom/detail",
  CLASSROOM_CREATE = "/classroom/create",
  PLAN = "/plan",
  PLAN_DETAIL = "/plan/detail",
  PLAN_CREATE = "/plan/create",
  GROUP = "/group",
  GROUP_DETAIL = "/group/detail",
  GROUP_CREATE = "/group/create",
  TERM = "/term",
  TERM_DETAIL = "/term/detail",
  TERM_CREATE = "/term/create",
  TEACHER_SCHEDULE = "/schedule-teacher",
  TEACHER_SCHEDULE_DETAIL = "/schedule-teacher/detail",
  TEACHER_SCHEDULE_CREATE = "/schedule-teacher/create",
}
